### ISSUE TITLE
Refactor into smaller plugins? Or at least more functions

### ISSUE THREAD

**Issue by barestides** [ArcaneMinecraft/ArcaneSurvival#1]
It may make sense to keep the donor commands in a separate plugin, as suggested by @SimonOrJ . 

Dumping everything into the onCommand method is super messy. A lot of the static message strings should be stored in separate class, maybe even an external yml file or something.  Almost definitely need to refactor how messages that are multiple lines get sent, to get rid of this repeated `p.message (...)` nonsense. Probably could just loop through an array of the lines you want to send to a player.

**Comment by chuushi** [comment]
I moved all the help messages to the separate class, as about half of the code came from that. :D
