### ISSUE TITLE
/afk: kick player when they're attacked/about to die

### ISSUE THREAD

**Issue by chuushi** [ArcaneMinecraft/ArcaneSurvival#13]
and disable pvp for that player while they're afk.

(This may end up in making our own pvp toggle module)

**Comment by barestides** [comment]
I agree with disabling pvp; but I feel that if you go afk, it's your responsibility to make sure you're in a safe spot.

**Comment by chuushi** [comment]
It would be, but as a player, I've been in some cases where I had to suddenly go away from my computer to find myself dead when I came back.  Happened to few other players on the server too, which would cause them to rage-quit or get frustrated at least.

I thought auto-kick upon attack will save some people some headache.

**Comment by chuushi** [comment]
Done
