### ISSUE TITLE
Diamond Ore Logging File

### ISSUE THREAD

**Issue by chuushi** [ArcaneMinecraft/ArcaneSurvival#2]
https://github.com/ArcaneMinecraft/ArcaneSurvival/blob/master/src/main/java/com/arcaneminecraft/survival/ArcaneSurvival.java#L241

We have CoreProtect that records diamond mining pretty reliably.  Do we still need to collect diamond data?

**Comment by barestides** [comment]
Probably not

**Comment by chuushi** [comment]
Okay, the code was removed (for slight efficiency, I guess)
